export const HOME = {
  TITLE: 'HOME_TITLE',
  IDEA_LOGO: 'HOME_IDEA_LOGO',
  ANDROID_LOGO: 'HOME_ANDROID_LOGO',
  APPLE_LOGO: 'HOME_APPLE_LOGO',
  ANDROID_BUTTON: 'HOME_ANDROID_BUTTON',
  APPLE_BUTTON: 'HOME_APPLE_BUTTON',
  BODY_TEXT: 'HOME_BODY_TEXT',
  APP_SCREENSHOT: 'HOME_APP_SCREENSHOT',
  CARD_TITLE: 'HOME_CARD_TITLE',
  CARD_ICON: 'HOME_CARD_ICON',
  CARD_LINK: 'HOME_CARD_LINK',
};
